Algoritmo "somadornumerico"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/7/2023
Var
// Seção de Declarações das variáveis 
     cont,n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   cont <- 1
    Enquanto (cont <= 10) faca
     Escreval("Informe o numero:")
      Leia(n)
     cont <- cont + 1
    FimEnquanto

Fimalgoritmo